In [85]:
import pandas as pd
import datetime as dt

In [49]:
state_scripts = pd.read_csv('https://www.dropbox.com/s/cgkw4zp5bjc7z2w/arcos-al-statewide-itemized.csv.gz?dl=1', compression='gzip')
state_scripts.head()

/var/folders/n2/5x35hhp53jg1kc9jxswsqhww0000gn/T/ipykernel_31590/1787879430.py:1: DtypeWarning: Columns (3,5,22,25,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  state_scripts = pd.read_csv('https://www.dropbox.com/s/cgkw4zp5bjc7z2w/arcos-al-statewide-itemized.csv.gz?dl=1', compression='gzip')

,REPORTER_DEA_NO,REPORTER_BUS_ACT,REPORTER_NAME,REPORTER_ADDL_CO_INFO,REPORTER_ADDRESS1,REPORTER_ADDRESS2,REPORTER_CITY,REPORTER_STATE,REPORTER_ZIP,REPORTER_COUNTY,...,DOSAGE_UNIT,TRANSACTION_ID,Product_Name,Ingredient_Name,Measure,MME_Conversion_Factor,Combined_Labeler_Name,Reporter_family,dos_str,MME
0,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,NaN,5500 NEW HORIZONS BLVD,NaN,NORTH AMITYVILLE,NY,11701,SUFFOLK,...,1000.0,733,HYDROCODONE.BIT & ACETA 10MG & 500M,HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,TAB,1.0,Par Pharmaceutical,Bellco Drug Corp,10.0,6054.000
1,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,NaN,5500 NEW HORIZONS BLVD,NaN,NORTH AMITYVILLE,NY,11701,SUFFOLK,...,300.0,140,HYDROCODONE BIT./IBUPROFEN;7.5MG & 2,HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,TAB,1.0,"Teva Pharmaceuticals USA, Inc.",Bellco Drug Corp,7.5,1362.150
2,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,NaN,5500 NEW HORIZONS BLVD,NaN,NORTH AMITYVILLE,NY,11701,SUFFOLK,...,500.0,4119,HYDROCODONE BIT.7.5MG/ACETAMINOPHEN,HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,TAB,1.0,"Actavis Pharma, Inc.",Bellco Drug Corp,7.5,2270.250
3,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,NaN,5500 NEW HORIZONS BLVD,NaN,NORTH AMITYVILLE,NY,11701,SUFFOLK,...,30.0,4222,HYDROCODONE BIT & ACETA 7.5MG/500MG,HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,TAB,1.0,Par Pharmaceutical,Bellco Drug Corp,7.5,136.215
4,PB0034861,DISTRIBUTOR,BELLCO DRUG CORP,NaN,5500 NEW HORIZONS BLVD,NaN,NORTH AMITYVILLE,NY,11701,SUFFOLK,...,6000.0,2367,HYDROCODONE BIT & ACETA 7.5MG/500MG,HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,TAB,1.0,Par Pharmaceutical,Bellco Drug Corp,7.5,27243.000

In [50]:
state_scripts.loc[state_scripts['BUYER_STATE'] == 'AL','BUYER_COUNTY']

0          COVINGTON
1          COVINGTON
2          COVINGTON
3          COVINGTON
4             WALKER
             ...
5159810       ETOWAH
5159811       ETOWAH
5159812       ETOWAH
5159813      RUSSELL
5159814      HOUSTON
Name: BUYER_COUNTY, Length: 5159815, dtype: object

In [87]:
state_scripts.columns
script_columns = ['BUYER_STATE', 'BUYER_COUNTY', 'DRUG_NAME', 'TRANSACTION_DATE','Product_Name', 'Ingredient_Name', 'MME']
only_scripts = state_scripts[script_columns]
only_scripts['trans_date'] = pd.to_datetime(only_scripts['TRANSACTION_DATE'], format='%m%d%Y')
only_scripts.loc[only_scripts['BUYER_STATE'] == 'AL']

/var/folders/n2/5x35hhp53jg1kc9jxswsqhww0000gn/T/ipykernel_31590/931344998.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_scripts['trans_date'] = pd.to_datetime(only_scripts['TRANSACTION_DATE'], format='%m%d%Y')

,BUYER_STATE,BUYER_COUNTY,DRUG_NAME,TRANSACTION_DATE,Product_Name,Ingredient_Name,MME,trans_date
0,AL,COVINGTON,HYDROCODONE,3022006,HYDROCODONE.BIT & ACETA 10MG & 500M,HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,6054.000,2006-03-02
1,AL,COVINGTON,HYDROCODONE,7032006,HYDROCODONE BIT./IBUPROFEN;7.5MG & 2,HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,1362.150,2006-07-03
2,AL,COVINGTON,HYDROCODONE,12132006,HYDROCODONE BIT.7.5MG/ACETAMINOPHEN,HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,2270.250,2006-12-13
3,AL,COVINGTON,HYDROCODONE,12132006,HYDROCODONE BIT & ACETA 7.5MG/500MG,HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,136.215,2006-12-13
4,AL,WALKER,HYDROCODONE,4072007,HYDROCODONE BIT & ACETA 7.5MG/500MG,HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,27243.000,2007-04-07
...,...,...,...,...,...,...,...,...
5159810,AL,ETOWAH,OXYCODONE,8122009,OXYCODONE HYDROCHLORIDE 40MG TABS.,OXYCODONE HYDROCHLORIDE,10758.000,2009-08-12
5159811,AL,ETOWAH,OXYCODONE,1252010,OXYCODONE HYDROCHLORIDE 30MG TABLET,OXYCODONE HYDROCHLORIDE,40342.500,2010-12-05
5159812,AL,ETOWAH,HYDROCODONE,8082012,HYDROCODONE BIT & ACETA 7.5MG/500MG,HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,4540.500,2012-08-08
5159813,AL,RUSSELL,OXYCODONE,3062008,OXYCODONE.HCL ER 20MG TABS,OXYCODONE HYDROCHLORIDE,2689.500,2008-03-06
5159814,AL,HOUSTON,HYDROCODONE,8282008,HYDROCODONE BIT. & ACETA 5MG/500MG T,HYDROCODONE BITARTRATE HEMIPENTAHYDRATE,6054.000,2008-08-28

In [35]:
state_pop = pd.read_csv('../00_source_data/US_Population/start_2000.csv', encoding='latin-1')
state_pop.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2000POP,ESTIMATESBASE2000,POPESTIMATE2000,...,RDOMESTICMIG2009,RNETMIG2001,RNETMIG2002,RNETMIG2003,RNETMIG2004,RNETMIG2005,RNETMIG2006,RNETMIG2007,RNETMIG2008,RNETMIG2009
0,40,3,6,1,0,Alabama,Alabama,4447100,4447382,4451849,...,2.353249,-0.684621,-0.770328,1.879725,2.511446,4.862851,8.802178,4.833042,4.795516,3.486618
1,50,3,6,1,1,Alabama,Autauga County,43671,43671,43872,...,3.105529,7.315471,11.786898,9.458969,21.489832,15.189393,21.840681,10.127452,4.451631,3.125309
2,50,3,6,1,3,Alabama,Baldwin County,140415,140415,141358,...,16.080204,21.274961,19.220207,20.883915,29.953289,34.010472,32.487616,21.257958,16.342575,17.293381
3,50,3,6,1,5,Alabama,Barbour County,29038,29038,29035,...,-6.345156,-5.115177,-5.434783,-1.463357,-8.008416,-8.827024,-4.745119,-5.531944,0.738602,-4.498682
4,50,3,6,1,7,Alabama,Bibb County,20826,19889,19936,...,-1.111729,45.354469,-0.858676,2.712994,7.101432,7.279900,-5.250820,6.453121,3.343084,-0.787475

In [41]:
pop_columns = ['STNAME', 'CTYNAME', 'POPESTIMATE2000', 'POPESTIMATE2001', 'POPESTIMATE2002','POPESTIMATE2003', 
'POPESTIMATE2004','POPESTIMATE2005', 'POPESTIMATE2006','POPESTIMATE2007', 'POPESTIMATE2008', 'POPESTIMATE2009']
al_pop = state_pop[state_pop['STNAME'] == 'Alabama']
al_pop[pop_columns]

In [63]:
state_deaths_03 = pd.read_table('../00_source_data/US_VitalStatistics/Underlying Cause of Death, 2003.txt')
al_deaths_03 = state_deaths_03.copy()

In [64]:
al_deaths_03.drop('Notes', axis=1, inplace=True)
al_deaths_03.dropna(how='all', inplace=True)
al_deaths_03

,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
0,"Autauga County, AL",1001.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,397.0
1,"Baldwin County, AL",1003.0,2003.0,2003.0,Drug poisonings (overdose) Unintentional (X40-...,D1,10.0
2,"Baldwin County, AL",1003.0,2003.0,2003.0,All other alcohol-induced causes,A9,14.0
3,"Baldwin County, AL",1003.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,1479.0
4,"Barbour County, AL",1005.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,287.0
...,...,...,...,...,...,...,...
4082,"Sweetwater County, WY",56037.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,272.0
4083,"Teton County, WY",56039.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,85.0
4084,"Uinta County, WY",56041.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,111.0
4085,"Washakie County, WY",56043.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,88.0
4086,"Weston County, WY",56045.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,63.0

In [82]:
only_od = al_deaths_03[al_deaths_03['Drug/Alcohol Induced Cause'].str.contains('Drug poisonings')]
only_od[['COUNTY', 'STATE']] = only_od['County'].str.split(',', 1, expand=True)
only_od

/var/folders/n2/5x35hhp53jg1kc9jxswsqhww0000gn/T/ipykernel_31590/3455202757.py:2: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  only_od[['COUNTY', 'STATE']] = only_od['County'].str.split(',', 1, expand=True)
/var/folders/n2/5x35hhp53jg1kc9jxswsqhww0000gn/T/ipykernel_31590/3455202757.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_od[['COUNTY', 'STATE']] = only_od['County'].str.split(',', 1, expand=True)
/var/folders/n2/5x35hhp53jg1kc9jxswsqhww0000gn/T/ipykernel_31590/3455202757.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  only_od[['COUNTY', 'STATE']] = only_od['County'].str.split(',', 1, expand=True)

,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths,COUNTY,STATE
1,"Baldwin County, AL",1003.0,2003.0,2003.0,Drug poisonings (overdose) Unintentional (X40-...,D1,10.0,Baldwin County,AL
38,"Jefferson County, AL",1073.0,2003.0,2003.0,Drug poisonings (overdose) Unintentional (X40-...,D1,37.0,Jefferson County,AL
54,"Mobile County, AL",1097.0,2003.0,2003.0,Drug poisonings (overdose) Unintentional (X40-...,D1,26.0,Mobile County,AL
78,"Anchorage Borough, AK",2020.0,2003.0,2003.0,Drug poisonings (overdose) Unintentional (X40-...,D1,31.0,Anchorage Borough,AK
91,"Matanuska-Susitna Borough, AK",2170.0,2003.0,2003.0,Drug poisonings (overdose) Unintentional (X40-...,D1,11.0,Matanuska-Susitna Borough,AK
...,...,...,...,...,...,...,...,...,...
3985,"Dane County, WI",55025.0,2003.0,2003.0,Drug poisonings (overdose) Unintentional (X40-...,D1,24.0,Dane County,WI
4017,"Milwaukee County, WI",55079.0,2003.0,2003.0,Drug poisonings (overdose) Unintentional (X40-...,D1,120.0,Milwaukee County,WI
4018,"Milwaukee County, WI",55079.0,2003.0,2003.0,Drug poisonings (overdose) Suicide (X60-X64),D2,20.0,Milwaukee County,WI
4033,"Racine County, WI",55101.0,2003.0,2003.0,Drug poisonings (overdose) Unintentional (X40-...,D1,13.0,Racine County,WI
4053,"Waukesha County, WI",55133.0,2003.0,2003.0,Drug poisonings (overdose) Unintentional (X40-...,D1,17.0,Waukesha County,WI